---

- name: Ensure sites-enabled and sites_available exist
  file:
    name: '{{ item }}'
    state: directory
  with_items:
  - '/etc/nginx/sites-available'
  - '/etc/nginx/sites-enabled'

#- name: Print some debug information 
#  vars: 
#    msg: |
#        Module Variables ("vars"):
#        --------------------------------
#        {{ vars | to_nice_json }} 
# 
#        Environment Variables ("environment"):
#        --------------------------------
#        {{ environment | to_nice_json }} 
# 
#        GROUP NAMES Variables ("group_names"):
#        --------------------------------
#        {{ group_names | to_nice_json }}
# 
#        GROUPS Variables ("groups"):
#        --------------------------------
#        {{ groups | to_nice_json }}
# 
#        HOST Variables ("hostvars"):
#        --------------------------------
#        {{ hostvars | to_nice_json }} 
# 
#  debug: 
#    msg: "{{ msg.split('\n') }}"       
#  tags: debug_info

- name: Install site
  template:
    src: site.conf
    dest: '/etc/nginx/sites-available/{{ nginx_site_name }}.conf'
  notify: reload nginx

- name: Enable site
  file:
    src: '/etc/nginx/sites-available/{{ nginx_site_name }}.conf'
    dest: '/etc/nginx/sites-enabled/50-{{ nginx_site_name }}.conf'
    state: link
  when: nginx_site_enabled
  notify: reload nginx

- name: Disable site
  file:
    dest: '/etc/nginx/sites-enabled/50-{{ nginx_site_name }}.conf'
    state: absent
  when: not nginx_site_enabled
  notify: reload nginx
